spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/scott?
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: scott
    password: tiger

thymeleaf:
  prefix: classpath:/templates/
  suffix: html
  mode: HTML5
  cache: false

server:
  port: 8091
